// Constants
export const ERROR_MESSAGES = {
  EXCEED_MAX_BALANCE: 'Your amount exceeds maximum balance.',
  FAIL_TO_SWITCH_NETWORK: 'Failed to switch network',
  WALLET_NOT_CONNECTED: 'Please connect wallet first',
  ACCOUNT_NOT_CREATED: 'Please create account first',
  INVALID_TX_DATA: 'Invalid transaction data',
  SEND_TX_FAILED: 'Send transaction failed',
  WITHDRAW_FAILED: 'Withdraw failed',
  DEPOSIT_FAILED: 'Deposit failed',
  CREATE_ACCOUNT_FAILED: 'Create account failed',
  CREATE_AUTHORITY_FAILED: 'Create authority failed',
  DELETE_AUTHORITY_FAILED: 'Delete authority failed',
  INVALID_ADDRESS: 'Invalid address',
  BUY_TOKEN_FAILED: 'Buy token failed',
  SELL_TOKEN_FAILED: 'Sell token failed',
  CREATE_TOKEN_FAILED: 'Create token failed',
  REGISTER_FAILED: 'Register nad name failed',
  SET_PRIMARY_NAME_FAILED: 'Set primary name failed',
} as const;

export const SUCCESS_MESSAGES = {
  WITHDRAW_SUCCESS: 'Withdraw successfully',
  REQUEST_WITHDRAW_SUCCESS: 'Request withdraw successfully',
  CLAIM_SUCCESS: 'Claim successfully',
  DEPOSIT_SUCCESS: 'deposit successfully',
  CREATE_ACCOUNT_SUCCESS: 'Create account successfully',
  CREATE_AUTHORITY_SUCCESS: 'Create authority successfully',
  DELETE_AUTHORITY_SUCCESS: 'Delete authority successfully',
  BUY_TOKEN_SUCCESS: 'Token bought successfully',
  SELL_TOKEN_SUCCESS: 'Token sold successfully',
  CREATE_TOKEN_SUCCESS: 'Token created successfully',
  REGISTER_SUCCESS: 'Nad name registered successfully',
  SET_PRIMARY_NAME_SUCCESS: 'Primary name set successfully',
} as const;
