// Constants
export const ERROR_MESSAGES = {
  EXCEED_MAX_BALANCE: 'Your amount exceeds maximum balance.',
  FAIL_TO_SWITCH_NETWORK: 'Failed to switch network',
  WALLET_NOT_CONNECTED: 'Please connect wallet first',
  WALLET_ADDRESS_REQUIRED: 'Please enter wallet address',
  ACCOUNT_ADDRESS_REQUIRED: 'Please select account address',
  INVALID_WALLET_ADDRESS: 'Invalid wallet address',
  ACCOUNT_NOT_CREATED: 'Please create account first',
  INVALID_TX_DATA: 'Invalid transaction data',
  SEND_TX_FAILED: 'Send transaction failed',
  WITHDRAW_FAILED: 'Withdrawal failed',
  DEPOSIT_FAILED: 'Deposit failed',
  CLAIM_FAILED: 'Claim failed',
  TOKEN_CLAIM_FAILED: 'Token claim failed', //new
  REWARDS_CLAIM_FAILED: 'Rewards claim failed', //new
  CREATE_ACCOUNT_FAILED: 'Account creation failed',
  CREATE_AUTHORITY_FAILED: 'Adding authority failed',
  DELETE_AUTHORITY_FAILED: 'Removing authority failed',
  INVALID_ADDRESS: 'Invalid address',
  BUY_TOKEN_FAILED: 'Token purchase failed',
  SELL_TOKEN_FAILED: 'Token sale failed',
  CREATE_TOKEN_FAILED: 'Token deployment failed',
  REGISTER_FAILED: 'Domain registration failed',
  SET_PRIMARY_NAME_FAILED: 'Primary domain update failed',
  TRANSFER_NAME_FAILED: 'Domain transfer failed',
  SWAP_FAILED: 'Swap failed',
  TOP_UP_FAILED: 'Account funding failed',
  CREATE_POSITION_FAILED: 'Position creation failed',
  ADD_LIQUIDITY_FAILED: 'Adding liquidity failed', //new
  REMOVE_LIQUIDITY_FAILED: 'Removing liquidity failed',
  TRADE_FAILED: 'Trade failed',
  ORDER_CLOSED_FAILED: 'Order closing failed',
  ORDER_CANCELLED_FAILED: 'Order cancellation failed',
  TRANSFER_TO_TRADING_FAILED: 'Transfer to trading account failed',
  TRANSFER_TO_FUNDING_FAILED: 'Transfer to funding account failed',
  BADGE_PURCHASE_FAILED: 'Badge purchase failed',
  INSUFFICIENT_BALANCE: 'Insufficient balance',
  FAUCET_AIRDROP_FAILED: 'Faucet claim failed',
  IMAGE_UPLOAD_FAILED: 'Image upload failed',
  CHECK_IN_FAILED: 'Check in failed',
} as const;

export const SUCCESS_MESSAGES = {
  WITHDRAW_SUCCESS: 'Withdrawal successful',
  REQUEST_WITHDRAW_SUCCESS: 'Withdrawal request submitted',
  CLAIM_SUCCESS: 'Claimed successfully',
  TOKEN_CLAIM_SUCCESS: 'Token claimed successfully', //new
  REWARDS_CLAIM_SUCCESS: 'Rewards claimed successfully', //new
  DEPOSIT_SUCCESS: 'Deposit successful',
  CREATE_ACCOUNT_SUCCESS: 'Account created successfully',
  CREATE_AUTHORITY_SUCCESS: 'Authority added successfully',
  DELETE_AUTHORITY_SUCCESS: 'Authority removed successfully',
  BUY_TOKEN_SUCCESS: 'Token purchased successfully',
  SELL_TOKEN_SUCCESS: 'Token sold successfully',
  CREATE_TOKEN_SUCCESS: 'Token deployed successfully',
  REGISTER_SUCCESS: 'Domain registered successfully',
  SET_PRIMARY_NAME_SUCCESS: 'Primary domain updated successfully',
  TRANSFER_NAME_SUCCESS: 'Domain transferred successfully',
  SWAP_SUCCESS: 'Swap completed successfully',
  TOP_UP_SUCCESS: 'Account funded successfully',
  CREATE_POSITION_SUCCESS: 'Position created successfully',
  ADD_LIQUIDITY_SUCCESS: 'Liquidity added successfully', //new
  REMOVE_LIQUIDITY_SUCCESS: 'Liquidity removed successfully',
  TRADE_SUCCESS: 'Trade completed successfully',
  ORDER_CLOSED_SUCCESS: 'Order closed successfully',
  ORDER_CANCELLED_SUCCESS: 'Order cancelled successfully',
  TRANSFER_TO_TRADING_SUCCESS: 'Transferred to trading account successfully',
  TRANSFER_TO_FUNDING_SUCCESS: 'Transferred to funding account successfully',
  BADGE_PURCHASE_SUCCESS: 'Badge purchased successfully',
  FAUCET_AIRDROP_SUCCESS: 'Faucet claimed successfully',
  IMAGE_UPLOAD_SUCCESS: 'Image uploaded successfully',
  CHECK_IN_SUCCESS: 'Check in successfully',
} as const;
